version: '3.2'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    environment:
      # Default user and database will be created using `init-defaults.sh` script
      CLICKHOUSE_DB: nginx
      CLICKHOUSE_USER: root
      CLICKHOUSE_PASSWORD: root
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
