[sources.track]
type = "file"
include = ["./data/example.log"]
read_from = "end"

[transforms.process]
type = "remap"
inputs = ["track"]
source = '''
. |= parse_regex!(.message, r'^(?P<ip>\d+\.\d+\.\d+\.\d+) \- (?P<date>\d+\-\d+\-\d+)T(?P<time>\d+:\d+:\d+).+?"(?P<url>.+?)" (?P<status>\d+) (?P<size>\d+) "(?P<agent>.+?)"$')
.status = to_int!(.status)
.size = to_int!(.size)
.time = .date + " " + .time
'''

[sinks.clickhouse]
type = "clickhouse"
inputs = ["process"]
endpoint = "http://host.docker.internal:8123"
auth.strategy = "basic"
auth.user = "root"
auth.password = "root"
batch.max_events = 100
batch.timeout_secs = 1
database = "nginx"
table = "log"
skip_unknown_fields = true
